import { Consultation } from './consultation.model';
import { Review } from './review.model';
import { User } from './user.model';
import { Location } from './location.model';
export interface Property { 
  _id?: string;
  title: string;
  description: string;
  propertyType: string;
  location: string | Location;
  spaceType: string;
  rentType: string;
  height?: number;
  length?: number;
  width?: number;
  utilities?: string[];
  constructionType?: string;
  amenities: string[];
  accessTime: string;
  floor: number;
  accessFacilities?: string[];
  additionalEquipment?: string[];
  security: string[];
  minimumRecommendedPrice: number;
  recommendedMaximumPrice: number;
  price: number;
  publicationPrice: number;
  discountInFirstMonth?: boolean;
  discount?: number;
  minimumMonthsDiscount?: number;
  insured: boolean;
  state?: string;
  photos: string[];
  lessor: string | User;
  visits?: number;
  reviews?: string[] | Review[];
  consultations?: string[] | Consultation[];
  createdAt?: Date;
  modifiedAt?: Date;
};
